//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.MVC.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade não encontrada na base de dados..
        /// </summary>
        public static string Cidade_Not_Found {
            get {
                return ResourceManager.GetString("Cidade_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe, mas ocorreu um erro ao processar sua informação no sistema..
        /// </summary>
        public static string Error_Call_Ajax {
            get {
                return ResourceManager.GetString("Error_Call_Ajax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] - Comunicar o Administrador do sistema informando o código do erro..
        /// </summary>
        public static string Error_Call_Mobile {
            get {
                return ResourceManager.GetString("Error_Call_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao executar as alterações..
        /// </summary>
        public static string Error_Save_Changes {
            get {
                return ResourceManager.GetString("Error_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Token enviado está incorreto ou inválido..
        /// </summary>
        public static string Error_Token_Validator {
            get {
                return ResourceManager.GetString("Error_Token_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado o arquivo na requisição HTTP..
        /// </summary>
        public static string Error_Upload_MimeMultipart {
            get {
                return ResourceManager.GetString("Error_Upload_MimeMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve uma falha ao autenticar o usuário. Tente novamente..
        /// </summary>
        public static string Failure_Sign {
            get {
                return ResourceManager.GetString("Failure_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto não encontrada na base de dados..
        /// </summary>
        public static string Foto_Not_Found {
            get {
                return ResourceManager.GetString("Foto_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Found_Register {
            get {
                return ResourceManager.GetString("Found_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Imei or Token Not found) - Invalid Request.
        /// </summary>
        public static string Imei_Or_Token_Not_Found {
            get {
                return ResourceManager.GetString("Imei_Or_Token_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo Json com a estrutura inválida..
        /// </summary>
        public static string Invalid_File_Upload {
            get {
                return ResourceManager.GetString("Invalid_File_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado o Ip na base de dados..
        /// </summary>
        public static string Ip_Not_Found {
            get {
                return ResourceManager.GetString("Ip_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não autenticado no sistema..
        /// </summary>
        public static string Not_Autenticated_Ajax {
            get {
                return ResourceManager.GetString("Not_Autenticated_Ajax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não autorizado para este recurso do sistema..
        /// </summary>
        public static string Not_Authorized_Ajax {
            get {
                return ResourceManager.GetString("Not_Authorized_Ajax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há registros cadastrados no banco de dados..
        /// </summary>
        public static string Not_Register_Data_Base {
            get {
                return ResourceManager.GetString("Not_Register_Data_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de Serviço não encontrada..
        /// </summary>
        public static string OS_Not_Found {
            get {
                return ResourceManager.GetString("OS_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste não encontrado na base de dados..
        /// </summary>
        public static string Poste_Not_Found {
            get {
                return ResourceManager.GetString("Poste_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterações salvas com sucesso..
        /// </summary>
        public static string Save_OK {
            get {
                return ResourceManager.GetString("Save_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A (Atualizado).
        /// </summary>
        public static string StatusComparativo_Poste_Atualizado {
            get {
                return ResourceManager.GetString("StatusComparativo_Poste_Atualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (Excluído).
        /// </summary>
        public static string StatusComparativo_Poste_Excluido {
            get {
                return ResourceManager.GetString("StatusComparativo_Poste_Excluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N (Novo).
        /// </summary>
        public static string StatusComparativo_Poste_Novo {
            get {
                return ResourceManager.GetString("StatusComparativo_Poste_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Token expired) - Invalid Request..
        /// </summary>
        public static string Token_Expired {
            get {
                return ResourceManager.GetString("Token_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformador não encontrado na base de dados..
        /// </summary>
        public static string Transformador_Not_Found {
            get {
                return ResourceManager.GetString("Transformador_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorretas..
        /// </summary>
        public static string User_Or_Passord_Incorrect {
            get {
                return ResourceManager.GetString("User_Or_Passord_Incorrect", resourceCulture);
            }
        }
    }
}
